module(
    name = "tasman_bazel_testing",
    version = "0.1.0",
)

# Bazel modules (bzlmod) is now enabled by default in Bazel 7+
# Add external dependencies here using bazel_dep()

bazel_dep(name = "abseil-cpp", version = "20240116.2")
bazel_dep(name = "imgui", version = "1.91.8")  
bazel_dep(name = "implot", version = "0.16")
bazel_dep(name = "googletest", version = "1.15.2")
bazel_dep(name = "pocketfft", version = "0.0.2")
bazel_dep(name = "hedron_compile_commands", dev_dependency = True)

git_override(
    module_name = "hedron_compile_commands",
    remote = "https://github.com/hedronvision/bazel-compile-commands-extractor.git",
    commit = "1e08f8e0507b6b6b1f4416a9a22cf5c28beaba93",
)

# Override imgui to use docking branch  
archive_override(
    module_name = "imgui",
    urls = ["https://github.com/ocornut/imgui/archive/v1.91.7-docking.tar.gz"],
    strip_prefix = "imgui-1.91.7-docking",
    integrity = "sha256-sVv5vA7OgOZqZTkmRlYpeaIgPhw/+k8dSOuRJq01LBM=",
    patches = [
        "//third_party:imgui_module.patch",
        "//third_party:imgui_build.patch",
        "//third_party:imgui_32bit_indices.patch",
    ],
    patch_strip = 1,
)